// This file contains the assistant's step-helper messages.
luminText = [
  "<h5>Let's begin. Enter your first name. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Enter your last name. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Enter your email address. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Enter your username. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Enter your password. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Re-enter your password. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Enter the first four digits your credit/debit card number. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Enter the next four digits your credit/debit card number. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Enter the next four digits your your credit/debit card number. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Enter the last four digits your your credit/debit card number. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Enter your credit/debit CCV. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Select your subscription start date. Then click OK.</h5><div class='row'><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='okAssistant' onclick='okClicked()'>OK</button></div><div class='col-md-6 text-center'><button type='button' class='btn btn-primary btn-xl' id='noAssistant' onclick='closeClicked()'>Close</button></div></div>",
  "<h5>Click submit.</h5>"

]
